# Generated by Django 4.1.7 on 2023-09-18 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("username", models.CharField(max_length=225, unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("first_name", models.CharField(blank=True, max_length=100, null=True)),
                ("last_name", models.CharField(blank=True, max_length=100, null=True)),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "verification_code",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("country", models.CharField(blank=True, max_length=255, null=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_superuser", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BotModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("modified_at", models.DateTimeField(auto_now_add=True)),
                ("symbol", models.CharField(max_length=200)),
                ("volume", models.DecimalField(decimal_places=2, max_digits=4)),
                ("grid_interval", models.IntegerField()),
                ("take_profit", models.IntegerField()),
                ("status", models.CharField(max_length=100)),
                ("close_trade", models.IntegerField(blank=True, null=True)),
                ("pip_margin", models.DecimalField(decimal_places=2, max_digits=4)),
                (
                    "side",
                    models.CharField(
                        choices=[("buy", "buy"), ("sell", "sell"), ("all", "all")],
                        default="all",
                        max_length=5,
                    ),
                ),
                (
                    "skip",
                    models.DecimalField(decimal_places=5, default=0, max_digits=6),
                ),
                (
                    "profit",
                    models.DecimalField(decimal_places=4, default=0, max_digits=10),
                ),
                (
                    "equity",
                    models.DecimalField(decimal_places=4, default=0, max_digits=20),
                ),
                (
                    "profit_margin",
                    models.DecimalField(decimal_places=4, default=50, max_digits=20),
                ),
                (
                    "min_combo",
                    models.DecimalField(decimal_places=4, default=0.5, max_digits=20),
                ),
                ("use_half_int", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TradeProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("modified_at", models.DateTimeField(auto_now_add=True)),
                ("mt5_login", models.IntegerField(unique=True)),
                ("mt5_password", models.CharField(max_length=150)),
                ("mt5_server", models.CharField(max_length=200)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trade_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OrderModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("modified_at", models.DateTimeField(auto_now_add=True)),
                ("order_id", models.IntegerField()),
                ("price", models.DecimalField(decimal_places=5, max_digits=10)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("buy", "buy"),
                            ("sell", "sell"),
                            ("deposit", "deposit"),
                            ("withdrawal", "withdrawal"),
                        ],
                        max_length=10,
                    ),
                ),
                ("take_profit", models.DecimalField(decimal_places=5, max_digits=10)),
                ("status", models.CharField(max_length=100)),
                (
                    "bot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="api.botmodel",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="botmodel",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bots",
                to="api.tradeprofile",
            ),
        ),
        migrations.CreateModel(
            name="ApiKeyModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=225)),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_keys",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
