# Generated by Django 4.1 on 2022-09-30 13:11

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=200)),
                ('volume', models.DecimalField(decimal_places=2, max_digits=4)),
                ('grid_interval', models.IntegerField()),
                ('take_profit', models.IntegerField()),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUserModel',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('mt5_login', models.BigIntegerField()),
                ('mt5_password', models.CharField(max_length=225)),
                ('mt5_server', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=5, max_digits=5)),
                ('volume', models.DecimalField(decimal_places=2, max_digits=4)),
                ('type', models.CharField(choices=[('buy', 'buy'), ('sell', 'sell')], max_length=10)),
                ('take_profit', models.DecimalField(decimal_places=5, max_digits=5)),
                ('status', models.CharField(max_length=100)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='api.botmodel')),
            ],
        ),
        migrations.AddField(
            model_name='botmodel',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bots', to='api.customusermodel'),
        ),
    ]
