# Generated by Django 4.1.7 on 2024-04-16 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="botmodel",
            name="ratio",
            field=models.DecimalField(decimal_places=0, default=0, max_digits=3),
        ),
    ]
