# Generated by Django 4.1.1 on 2022-09-27 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botmodel',
            name='type',
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='type',
            field=models.CharField(choices=[('buy', 'buy'), ('sell', 'sell')], default='buy', max_length=10),
        ),
    ]
