# Generated by Django 4.1.7 on 2023-05-12 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="botmodel",
            name="use_half_int",
            field=models.BooleanField(default=False),
        ),
    ]
