# Generated by Django 4.1.1 on 2022-09-27 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_botmodel_type_ordermodel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='type',
            field=models.CharField(choices=[('buy', 'buy'), ('sell', 'sell')], max_length=10),
        ),
    ]
