# Generated by Django 4.1.4 on 2023-01-17 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_apikeymodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="botmodel",
            name="pip_margin",
            field=models.DecimalField(decimal_places=2, default=3.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name="ordermodel",
            name="price",
            field=models.DecimalField(decimal_places=5, max_digits=6),
        ),
        migrations.AlterField(
            model_name="ordermodel",
            name="take_profit",
            field=models.DecimalField(decimal_places=5, max_digits=6),
        ),
        migrations.AlterField(
            model_name="tradeprofile",
            name="mt5_login",
            field=models.IntegerField(unique=True),
        ),
    ]
