# Generated by Django 4.1.7 on 2023-05-04 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_apikeymodel_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="botmodel",
            name="close_trade",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
