# Generated by Django 4.1.4 on 2023-02-06 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_botmodel_pip_margin"),
    ]

    operations = [
        migrations.AddField(
            model_name="botmodel",
            name="sides",
            field=models.CharField(
                choices=[("buy", "buy"), ("sell", "sell"), ("all", "all")],
                default="all",
                max_length=5,
            ),
        ),
    ]
