# Generated by Django 4.1.4 on 2023-02-06 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_botmodel_sides"),
    ]

    operations = [
        migrations.RenameField(
            model_name="botmodel",
            old_name="sides",
            new_name="side",
        ),
    ]
