# Generated by Django 4.1.6 on 2023-02-15 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_rename_sides_botmodel_side"),
    ]

    operations = [
        migrations.AddField(
            model_name="botmodel",
            name="skip",
            field=models.IntegerField(default=0),
        ),
    ]
