# Generated by Django 4.1.6 on 2023-02-15 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_botmodel_skip"),
    ]

    operations = [
        migrations.AlterField(
            model_name="botmodel",
            name="skip",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
