# Generated by Django 4.1.6 on 2023-02-15 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_alter_botmodel_skip"),
    ]

    operations = [
        migrations.AlterField(
            model_name="botmodel",
            name="skip",
            field=models.DecimalField(decimal_places=5, default=0, max_digits=6),
        ),
    ]
