# Generated by Django 4.1.6 on 2023-02-20 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_alter_botmodel_skip"),
    ]

    operations = [
        migrations.AddField(
            model_name="botmodel",
            name="profit",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
    ]
