# Generated by Django 4.1.7 on 2023-02-20 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_botmodel_profit"),
    ]

    operations = [
        migrations.AddField(
            model_name="botmodel",
            name="equity",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20),
        ),
    ]
