# Generated by Django 4.1.7 on 2023-02-21 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_botmodel_equity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordermodel",
            name="price",
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name="ordermodel",
            name="take_profit",
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
    ]
