# Generated by Django 4.1.7 on 2023-03-08 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_alter_ordermodel_price_alter_ordermodel_take_profit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordermodel",
            name="type",
            field=models.CharField(
                choices=[
                    ("buy", "buy"),
                    ("sell", "sell"),
                    ("deposit", "deposit"),
                    ("withdrawal", "withdrawal"),
                ],
                max_length=10,
            ),
        ),
    ]
