# Generated by Django 4.1.7 on 2023-04-29 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_alter_ordermodel_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="botmodel",
            name="min_combo",
            field=models.DecimalField(decimal_places=4, default=0.5, max_digits=20),
        ),
        migrations.AddField(
            model_name="botmodel",
            name="profit_margin",
            field=models.DecimalField(decimal_places=4, default=50, max_digits=20),
        ),
    ]
